# Generated by Django 5.0.6 on 2024-07-24 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0003_orderidgen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orderidgen',
        ),
    ]
