# Generated by Django 5.0.6 on 2024-07-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0008_trsdetail_delete_trsdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.PositiveIntegerField(),
        ),
    ]
