# Generated by Django 5.0.6 on 2024-07-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0009_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trsdetail',
            name='user',
            field=models.PositiveIntegerField(),
        ),
    ]
