# Generated by Django 5.0.6 on 2024-07-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0010_alter_trsdetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trsdetail',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI')], max_length=10),
        ),
    ]
