# Generated by Django 5.0.6 on 2024-07-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0011_alter_trsdetail_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=77, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order placed', 'Order placed'), ('Order Dispatched', 'Order Dispatched'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], default='Order Placed', max_length=50),
        ),
    ]
