# Generated by Django 5.0.6 on 2024-07-26 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0013_category_product_category_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
