# Generated by Django 5.0.6 on 2024-07-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0014_remove_product_subcategory_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='0000000', max_length=100),
        ),
    ]
