# Generated by Django 5.0.6 on 2024-07-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0015_alter_category_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
