# Generated by Django 5.0.6 on 2024-07-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0019_product_category_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.CharField(default='20', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='productname',
            field=models.CharField(default='20', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.CharField(default='20', max_length=150),
        ),
    ]
