# Generated by Django 5.0.6 on 2024-08-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0020_order_price_order_productname_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinery',
            name='quantity',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
