# Generated by Django 5.0.6 on 2024-08-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0022_alter_order_price_alter_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernews',
            name='description',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='usernews',
            name='heading',
            field=models.CharField(max_length=1500),
        ),
    ]
